# available library sub-areas, with available spaces
# this file is generated automatically by `seatlib.py`
# at: Fri May  5 12:19:53 2023
北馆(李文正馆):
  G层(现场选位):
    古籍阅览室: 0
  一层:
    A阅览区: 0
    B阅览区: 1
    C阅览区: 0
  三层:
    A阅览区: 18
    B阅览区: 140
    C阅览区: 40
    D阅览区: 56
    连廊: 12
  二层:
    A阅览区: 50
    B阅览区: 120
    C阅览区: 38
    D阅览区: 72
    E阅览区: 24
    连廊: 8
  五层:
    A阅览区: 16
    B阅览区: 44
    C阅览区: 40
  四层:
    A阅览区: 54
    B阅览区: 110
    C阅览区: 12
    D阅览区: 64
北馆古籍阅览室:
  G层:
    古籍阅览室: 14
文科图书馆:
  一层:
    C区: 28
    信息空间: 48
  三层:
    A区: 40
    B区: 48
    C区: 84
  二层:
    A区  【*部分座席配有扩展屏】: 40
    C区: 98
  四层:
    C区: 88
法律图书馆:
  三层:
    北阅览区: 84
    南阅览区(坡道): 85
    西阅览区: 108
  二层:
    东阅览区(坡道): 90
  五层:
    北阅览区: 14
  四层:
    东阅览区: 108
    北阅览区: 60
    西阅览区(坡道): 90
美术图书馆:
  三层:
    C阅览区: 10
    E阅览区: 36
  二层:
    C阅览区: 12
    E阅览区: 12
    N阅览区: 38
    S阅览区: 64
    W阅览区: 12
西馆(逸夫馆):
  三层:
    311阅览区: 80
    313阅览区: 72
    315阅览区: 12
    319阅览区: 12
    320阅览区: 24
    322阅览区: 8
    A阅览区: 70
  二层:
    206阅览区: 40
    216阅览区: 48
    220阅览区: 16
    222阅览区: 24
    224阅览区: 8
    225阅览区: 144
    227阅览区: 88
    231阅览区: 64
    233阅览区: 24
    A阅览区: 80
    B阅览区: 8
    L阅览区: 8
  四层:
    401培训教室: 0
    407阅览区: 20
    C阅览区: 4
    D阅览区: 4
西馆401阅览室:
  一层:
    A阅览区: 40
  四层:
    401培训教室: 60
金融图书馆:
  四层:
    A阅览区: 29
    B阅览区: 45
    C阅览区: 17
    D阅览区: 6
音乐馆:
  音乐馆:
    单人欣赏区（Individual）: 64
    团体视听区（Group）: 6
    电子阅览区（E-reading）: 16
