## this is the block list of seat codes
## the file must be loaded as a list of strings

## glob patterns may be used to specify blocked seat codes
## ... this is realized by the builtin `fnmatch` module
## ... see: https://docs.python.org/3/library/fnmatch.html

# ## temporary
# - 'F1C016'
- 'F1C009'

# ## too hot (for the summer)
- 'F1C00[1-8]'

## broken window shades
# humanities library
- 'F1C001'
- 'F1C004'
- 'F1C01[78]'

## window-less seats
# west area 315
- 'WF3E009'
- 'WF3E01[012]'
# west area 319
- 'WF3E02[1234]'
# humanities
- 'F1C02[5678]'
- 'F2C07[23456789]'
