## configure here the watched library areas
## ... from most preferred to least preferred
## ... see `areas.yml` for available areas

# ## a parent area must end with a colon (:)
# ## ... to foster the child areas
# 西馆:
# ## note that the colon (:) has to be "half-width" ascii
# ## "full-width" colon (：) in Chinese is not valid!

#   ## a single child with no descendant
#   ## ... can be listed on the same line as the parent
#   ## ... and need not end with a colon
#   二: 224
#   三:
#     ## multiple children can be collected in a list
#     ## ... in which the items are prefixed with a dash (-)
#     # - 315: ^2  # the book smell is too overwhelming
#     - 319: ^0
#     ## a minimal number of vacant seats may be specified
#     ## ... '^x' means that the program will not return
#     ## ... until there are strictly > x remaining seats
#     ## ... the default behavior is '^0'

文科图书馆:

  # area selectors can be suitably abbreviated
  # ... e.g. 一层 -> 一
  一: C
  # 二: C
  # 二: [C: ^1]  # bracket necessary, otherwise illegal yaml
  # 三: C
  # 四: C
